// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/types';
import type * as prismicClient from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *project → Galery*
 */
export interface ProjectDocumentDataGaleryItem {
  /**
   * Img1 field in *project → Galery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.galery[].img1
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img1: prismic.ImageField<never>;

  /**
   * Img2 field in *project → Galery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.galery[].img2
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img2: prismic.ImageField<never>;

  /**
   * img3 field in *project → Galery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.galery[].img3
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img3: prismic.ImageField<never>;

  /**
   * img4 field in *project → Galery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.galery[].img4
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img4: prismic.ImageField<never>;

  /**
   * img5 field in *project → Galery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.galery[].img5
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img5: prismic.ImageField<never>;
}

/**
 * Content for project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Type field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  type: prismic.KeyTextField;

  /**
   * Link_Online field in *project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.link_online
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_online: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Link_Github field in *project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.link_github
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_github: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Galery field in *project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.galery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  galery: prismic.GroupField<Simplify<ProjectDocumentDataGaleryItem>>;

  /**
   * Description_en field in *project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description_en
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description_en: prismic.RichTextField;

  /**
   * Description_ptBR field in *project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.description_ptbr
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description_ptbr: prismic.RichTextField;
}

/**
 * project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    'project',
    Lang
  >;

export type AllDocumentTypes = ProjectDocument;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismicClient.ClientConfig
    ): prismicClient.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismicClient.WriteClientConfig
    ): prismicClient.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismicClient.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataGaleryItem,
      AllDocumentTypes
    };
  }
}
