// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for project documents */
interface ProjectDocumentData {
    /**
     * Title field in *project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Type field in *project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.type
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    type: prismicT.KeyTextField;
    /**
     * Link field in *project*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: project.link
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    link: prismicT.LinkField;
    /**
     * Description field in *project*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: project.description
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    description: prismicT.KeyTextField;
    /**
     * Galery field in *project*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: project.galery[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    galery: prismicT.GroupField<Simplify<ProjectDocumentDataGaleryItem>>;
}
/**
 * Item in project → Galery
 *
 */
export interface ProjectDocumentDataGaleryItem {
    /**
     * Img1 field in *project → Galery*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.galery[].img1
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    img1: prismicT.ImageField<never>;
    /**
     * Img2 field in *project → Galery*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.galery[].img2
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    img2: prismicT.ImageField<never>;
    /**
     * img3 field in *project → Galery*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.galery[].img3
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    img3: prismicT.ImageField<never>;
    /**
     * img4 field in *project → Galery*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.galery[].img4
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    img4: prismicT.ImageField<never>;
    /**
     * img5 field in *project → Galery*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: project.galery[].img5
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    img5: prismicT.ImageField<never>;
}
/**
 * project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<ProjectDocumentData>, "project", Lang>;
export type AllDocumentTypes = ProjectDocument;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { ProjectDocumentData, ProjectDocumentDataGaleryItem, ProjectDocument, AllDocumentTypes };
    }
}
